### ISSUE TITLE
some clarification needed on Usage 

### ISSUE THREAD

**Issue by cristianvogel** [mifi/build-electron#2]
Hi,

thanks for having a go at this. 

I tried following your instructions. Bit confused about what `test` directory is in this repo? 
Can you clarify this part of your 'How To Use' section? 

> Put your Electron main ESM source code in src/main/index.js and preload source in src/preload/index.js.
> 
> Now create a configuration file in your project root build-electron.config.js:

Where is my project root in relation to build-electron project root? Is it inside it? Does it contain `src/main/*` like `myProject/src/main/*` and if so, where should the  `build-electron.config.js` and my package.js go in releation to `myProject/src` ? 

Just because first try didn't work and I realise its not really clear.

**Comment by mifi** [comment]
Hi!

`test` directory is just for running tests on the repo (in github actions). it is not part of the published npm module, and you can ignore it. Note that`build-electron` is not a boilerplate but it's supposed to be `yarn add -d build-electron`.

"Project root" means the directory where you have your package.json file in your project.

something like this::

```
📁 your project
  📄 package.json
  📄 build-electron.config.js
  📁 src
    📁 main/*
    📁 preload/*
```

hope it makes it more clear. i can update the readme

**Comment by cristianvogel** [comment]
yes i got it now... was going about it the wrong way, having cloned the build-electron repo into Webstorm, thinking I would build inside that test folder. I'll try the proper way now. Thankyou!
