### ISSUE TITLE
Import native module in ESM

### ISSUE THREAD

**Issue by thekingofcity** [mifi/build-electron#3]
Is it possible to import a native module that is published in ESM format? Form the doc, it suggests to exclude it.

`externals – Use this to [exclude](https://webpack.js.org/configuration/externals/) certain modules from being bundled, like native dependencies.`

**Comment by mifi** [comment]
Hi. That’s a good question! I think that most native modules I used were still in cjs format, but we should support esm too. Which module are you talking about?

**Comment by thekingofcity** [comment]
> I think that most native modules I used were still in cjs format

That's true and node doesn't support native esm import yet. You need to `import { createRequire } from 'module';` and `const require = createRequire(import.meta.url);`. From https://nodejs.org/api/esm.html#esm_no_native_module_loading

> Which module are you talking about?

A module built by myself. 🤣 So technically I can publish it in cjs format but I'm just looking for some solutions/workarounds. The electron community is moving so slowly.

It is `@thekingofcity/pravega`, a client for a distributed streaming storage system, and is not stable yet. I hope I could publish it in one format instead of maintaining two 'conflicting' formats.

https://github.com/thekingofcity/pravega-client-rust/tree/e88a27550d7212f3ffb6ab8f40bc13ba07aaa90e/nodejs

**Comment by thekingofcity** [comment]
I release the module in cjs, so there should be no more issues.
